### ISSUE TITLE
"selection" attribute better be "oneof"

### ISSUE THREAD

**Issue by sirkon** [sg3des/argum#5]
Kind of constraint that is called "selection" in the library is traditionally named as "oneof":
* https://developers.google.com/protocol-buffers/docs/proto3#oneof
* https://github.com/json-schema/json-schema/wiki/anyOf,-allOf,-oneOf,-not

May be rename "selection", "sel" into "oneof", "oo"?

**Comment by sg3des** [comment]
Thank you, done cf0415aa980b0529270a6c7be6da56ae767b4120. But i think, `oneof` keyword for it is enough.

**Comment by sirkon** [comment]
Great! Thank you!
